apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fqgp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fqgp
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fqgp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fqgp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fqgp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wwsc-tenant/rhtap-demo-app/hacbs-test-project-fqgp@sha256:03ce0454b3595a30b86ebf3b60e3d8eb0b9463d4038b171922e94697d3ae8839
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
